### ISSUE TITLE
galaxy subparser parity with cwl

### ISSUE THREAD

**Issue by hexylena** [hexylena/argparse2tool#61]
they support `foo.py --generate` and `foo.py foo --generate` which does just a single subparser named `foo` rather than all. Need to figure out what they're doing differently and perhaps unify the code.

**Comment by erasche** [comment]
Very well could be. I'll probably refactor my half to match y'all's whenever I find time for it.

**Comment by erasche** [comment]
E.g. there's some significant overlap that could probably be refactored into something cleaner. https://github.com/erasche/argparse2tool/blob/master/argparse/__init__.py#L133 which I borrowed from https://github.com/erasche/argparse2tool/blob/master/argparse/__init__.py#L84

**Comment by bernt-matthias** [comment]
https://github.com/hexylena/argparse2tool/pull/65 writes subparsers to separate xml files if `--directory` parameter is given. 

`foo.py foo --generate` still does not work .. but I would find it not very handy to generate xml this way from the command line since one does not know the names of the subparsers.

**Comment by hexylena** [comment]
@bernt-matthias agreed, with --directory is good enough. I didn't consider the "have to enumerate submodules" case.
